### ISSUE TITLE
Discussion: Tidying up the README.md

### ISSUE THREAD

**Issue by zoidbergwill** [zoidbergwill/awesome-ebpf#1]
I'd like to figure out a sensible order for sections and how to break it into sub-sections, since some projects are FOSS and some are private/propietary.

Ideally I'd like to figure out a sustainable way to keep SNR of the repo high. I think ordering talks by year makes sense for evolving tech, but then I'm not sure if things that feature eBPF but not as a focus make sense in the repo, I think they do if they're of interest of people that wanna learn more about it.

**Comment by qmonnet** [comment]
The list has been completely reworked since this issue was opened. Tidying up and re-organising items will probably never really stop, that's more or less the purpose of such a list, but I think we can safely close this issue :)
