### ISSUE TITLE
Implement TODO

### ISSUE THREAD

**Issue by mcandre** [zoidbergwill/awesome-ebpf#16]
Thank you for posting this helpful Awesome list! Unfortunately, the TODO on *What is BPF?* was exactly what I was hoping for in this doc. Is this just a network packet filter, or something else?

**Comment by qmonnet** [comment]
Hi @mcandre, the whole interest of the list is to point you to the documents which can answer to this question ;).

BPF and especially it extended version, eBPF, are used for more than packet filtering nowadays. People are using it for tracing and monitoring things in the Linux kernel, or advanced and fast network packet processing. Some introductions I would recommend are [the LWN article](https://old.lwn.net/Articles/740157/) or [this recent blog post](https://blogs.igalia.com/dpino/2019/01/07/introduction-to-xdp-and-ebpf/).

As for the TODO, well, yeah, would be nice to have a small blurb here someday :).

**Comment by zoidbergwill** [comment]
I love Cilium's [BPF Reference Guide](https://cilium.readthedocs.io/en/v1.3/bpf/) too, but it's a bit heavy for a elevator pitch / light overview.

**Comment by qmonnet** [comment]
Done in commit aeed52e. Feel free to reopen if you find it unsatisfying.

**Comment by zoidbergwill** [comment]
Awesome. That looks  great.
