### ISSUE TITLE
Get the list referenced on https://github.com/sindresorhus/awesome

### ISSUE THREAD

**Issue by qmonnet** [zoidbergwill/awesome-ebpf#22]
We should try to get this list in order and to submit it for inclusion into the list of “awesome” material lists.

See [the requirements](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md).

Missing items, as far as I can see:

- [x] GitHub topics (the repo should have `awesome-list` and `awesome`, and I suppose `bpf` and `ebpf` at least).
- [x] Formatting should be fixed (all lines starting with a link, then “-” (dash) should be used to separate the description, which should be harmonised (case, punctuation)).
- [x] The BPF description may need to be moved above the ToC, as per their example.
- [x] We should run the `awesome-lint` tool to check if anything else is amiss (I didn't manage to make it work, on a quick attempt).
- [ ] They suggest to add a logo, but I don't see what we could use and it does not sound mandatory.
- [x] Submitter must review at least two other PRs for that other `awesome` repo.

**Comment by zoidbergwill** [comment]
I managed to get awesome-lint to run:

```
   1 remark-lint:awesome/badge
   1 remark-lint:awesome/github
 136 remark-lint:awesome/list-item
   2 remark-lint:awesome/spell-check
   1 remark-lint:awesome/toc
  51 remark-lint:list-item-bullet-indent
   1 remark-lint:no-dead-urls
```

**Comment by zoidbergwill** [comment]
What license do you think we should add? I'd be more comfortable adding your name than mine to the License too.

**Comment by zoidbergwill** [comment]
The dead URL is `[The VALE switch](http://info.iet.unipi.it/~luigi/vale/)`, which seems to be the same one [here](https://conferences.sigcomm.org/co-next/2012/eproceedings/conext/p61.pdf)

**Comment by qmonnet** [comment]
Hi @zoidbergwill, that's a nice set of tags you added to the repo, great! :) And it's good to read that you managed to run the linter.

Regarding the license, I'm not sure there is anything to update? The repo currently uses CC-0, I believe it is fine? Feel free to add my name in the waiver if it makes you feel more comfortable, but don't worry about me. Keep your name in the waiver, by all means, you're the one who created the project!

It looks like Luigi's page has moved indeed, and I couldn't find a working link to the previous content on VALE. The link to the paper as you provide looks like a good replacement to me. Alternatively, it looks like the GitHub repo is here: <https://github.com/luigirizzo/netmap>. Or even the man page: <https://www.unix.com/man-page/freebsd/4/vale/>. Whichever you prefer :)

**Comment by zoidbergwill** [comment]
I think the last tasks in the list are optional, other than reviewing some other PRs on that repo?

So maybe we should do that, and then go ahead and make a PR to add this list?

**Comment by qmonnet** [comment]
Sounds good to me. I made a quick PR here to move the BPF description to the top of the file, so we can check one more item in the list.

Do you have some time to look into the two PRs thing? I don't think I'll be able to do it this week.

**Comment by zoidbergwill** [comment]
I should be able to get to that this week.

**Comment by zoidbergwill** [comment]
I've reviewed some issues on their PRs, if anyone happens to review any others, feel free to comment them on the PR, and I can add them to the PR.

**Comment by qmonnet** [comment]
It just got merged, that was fast! Congrats!!
