### ISSUE TITLE
ebpf-samples points to 404

### ISSUE THREAD

**Issue by jonesmz** [zoidbergwill/awesome-ebpf#31]
ebpf-samples - A collection of compiled (as ELF object files) samples gathered from several projects, primarily intended to serve as test cases for user space verifiers.

**Comment by qmonnet** [comment]
Are we talking about this link: <https://github.com/vbpf/ebpf-samples>? It works for me. Could you please double-check?

**Comment by jonesmz** [comment]
I'm very sorry, I copy-pasted the wrong section.

It was this one that doesn't work:

Netronome sample network applications - Provides basic but complete examples of eBPF applications also compatible with hardware offload.

https://github.com/Netronome/bpf-samples/

**Comment by qmonnet** [comment]
Ok. Yes, I'm aware of this one. However I have good reasons to believe that the repository should be available again soon, so I'd suggest we keep the link for now. I'll leave the issue open so we don't forget to check again in the future.

In the meantime, if you wish to look at Netronome samples, you can check out forks like [mine](https://github.com/qmonnet/bpf-samples), or [this one](https://github.com/Casidi/netronome-bpf-samples) which seems to be more up-to-date.

**Comment by qmonnet** [comment]
Now back online, closing the issue. But thanks again for the report!
