### ISSUE TITLE
Using eBPF to hook tx packet

### ISSUE THREAD

**Issue by liuhycn** [zoidbergwill/awesome-ebpf#39]

**Comment by liuhycn** [comment]
I want to use ebpf to hook the packets sent by the NIC and modify them. I saw an example of using ebpf to hook the received packets by a NIC in the tutorial, but I did not find an example of hooking to send packets.

**Comment by qmonnet** [comment]
Hi, I am not sure what tutorial you refer to, or what this issue has to do with the current repository? This is not a tutorial, but simply a list of resources.

As for your question, writing programs to modify packets on the egress path works just like for ingress path. There's just the hooks that differ: You would attach to an egress qdisc with tc, (no XDP, as I don't believe egress XDP [is supported yet](https://lore.kernel.org/netdev/20200513014607.40418-10-dsahern@kernel.org/t/#mdb2241287220840c8f724db2df3d9796a00dfd14), at least [not in a straightforward way](https://lore.kernel.org/bpf/20201211024049.1444017-1-liuhangbin@gmail.com/)).
