### ISSUE TITLE
merbridge is a simple tool to acclerate your mesh with eBPF

### ISSUE THREAD

**Issue by pacoxu** [zoidbergwill/awesome-ebpf#72]
https://github.com/merbridge/merbridge/

Merbridge: use eBPF to accelerate your mesh

https://landscape.cncf.io/card-mode?category=service-mesh&grouping=category&selected=merbridge
It is also included in CNCF landscape.

I'm not sure which part should I add this project to. 

- https://istio.io/latest/blog/2022/merbridge/

**Comment by qmonnet** [comment]
Yes, makes sense to add Merbridge. Section [Projects Related to eBPF](https://github.com/zoidbergwill/awesome-ebpf#projects-related-to-ebpf) is likely the most appropriate. It's in no particular order, so you could append at the end or try to insert it close to something similar, if any.
